### ISSUE TITLE
USER STORY: Customize styling of recipe list

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#100]
As a **Site Owner**,

I want to **display the list of recipes with distinctive, customized and responsive styling**,

so that **I facilitate a positive user experience**

### Acceptance Criteria

1. The visual styling of the list of is distinctive
2. The styling is consistent with the rest of the site
3. The styling is responsive on all devices with a minimum viewport width of 320 px
### Tasks

- [x] check color contrasts with accessibility checker, adjust palette
- [x] use color variables in CSS
- [x] unify color palette

**Comment by blahosyl** [comment]
Updated colors in accordance with color themes #98
