### ISSUE TITLE
USER STORY: Enable email verification at signup

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#103]
As an **Admin**,

I want to **enable email verification at signup**,

so that **users are better protected from fraud**

### Acceptance Criteria

1. A verification email is sent to the user after signing up
2. The verification email contains a link. Once clicked, the account is ready to use
3. Without confirming the signup by email, the account cannot be used

### Tasks

- [x] create app password in Gmail
  NB: for private accounts, this is no longer reachable from the 2FA menu, only by direct link: [https://myaccount.google.com/apppasswords](https://myaccount.google.com/apppasswords)
- [x] add app password and email address to Heroku (`env.py` optional)
- [x] make email mandatory for users in `settings.py`
- [x] set up email backend and other params in `settings.py`
- [x] in the Admin panel, under Sites: change Domain name and Display name 
- [x] test that email appears in the Terminal when running in Dev and DEBUG=True
- [x] test that email is sent to the address used at registration when running in Prod and DEBUG=False

**Comment by blahosyl** [comment]
Current setup still produces a 500 error. It seems the app is trying to log in to the Google account with the username+password of the spicy app users.

**Comment by blahosyl** [comment]
Now works in Dev (emails show up in the Terminal), but not in Prod (nothing is broken anymore, but emails are not sent) with codeinstitute.net credentials.

**Comment by blahosyl** [comment]
Created app password with private test Google account. This produces an 500 server error for the first 2 times. After that, reloading+resubmitting the form results in no email.

However, an email was sent 2 times on Jun 14th, 17:10 and 17:12 CET. Have not managed to reproduce this.

**Comment by blahosyl** [comment]
Mentor: one should tread carefully, as there are some version incompatibility issues that affect sending email.

Tutoring (John): Tested it and found no issues. Also received email without probelms. Said that 500 issues can sometimes be a result of database rate limits



![Image](https://github.com/blahosyl/spicy/assets/26421503/4be9c5bd-7cb7-4c36-839a-f3a5fb67e587)

**Comment by blahosyl** [comment]
Further testing shows the feature working as intended
