### ISSUE TITLE
USER STORY: Add favicon and logo

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#116]
As a **Developer**,

I want to **add a favicon and logo to the site**,

so that **Visitors have an enhanced and positive experience**

### Acceptance Criteria

1. Favicon is added and visible
2. Logo is added to nav bar

### Tasks

- [x] find a graphic to serve as a favicon/logo

#### Favicon

- [x] convert graphic file to favicon files with favicon.io
- [x] add favicon files to `static/favicon`
- [x] add link to favicons in `base.html`

#### Logo

- [ ] add graphic file to nav bar in `base.html`
- [ ] adjust positioning and size

#### Deployment

- [ ] collect static files
- [ ] `DEBUG=False`
