### ISSUE TITLE
USER STORY: Fix display of images on recipe detail page

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#120]
As a **Visitor**,

I want to **view recipe images on various viewport sizes**,

so that **I can use a range of devices to visit the site.**

### Acceptance Criteria

1. The featured images is visible on all devices in scope
2. The image and the masthead are aligned on all devices (vertically or horizontally)
3. The image is sized/centered properly.

### Tasks

- [x] add image to small screens
- [x] make image placement responsive
- [x] make image sizing responsive
