### ISSUE TITLE
USER STORY: Style recipe list

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#124]
As a **Developer**,

I want to **present the list of recipes in a styled and responsive manner**,

so that **Visitors have a positive User Experience**

### Acceptance Criteria

1. Recipe cards are styled in a unified way
2. The card list is responsive on all viewports in scope

### Tasks

- [ ] make cards the came height
- [ ] add border to cards
- [ ] adjust card size
