### ISSUE TITLE
USER STORY: README Intro & add-ons

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#138]
As a **Developer**,

I want to **provide a succinct introduction, description, picture and badges for my project**,

so that **readers can get a sense of the project at a glance**

### Acceptance Criteria

1. All items listed below are filled in and visible on GitHub without login

### Tasks

- [x] Introduction (README)
- [x]  Shield.io badges
- [x]  Social picture for repo
- [x]  Description for repo
