### ISSUE TITLE
USER STORY: README: User Experience

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#139]
As a **Developer**,

I want to **provide comprehensive documentation of User Experience**,

so that **the reader can follow how the project meets the needs of its intended audience**

### Acceptance Criteria

1. List of User Stories are linked from or displayed in the README: [link](https://docs.google.com/spreadsheets/d/1QDYJlX4RVgoKokpcXgFkGtmrwcCMplf8XZcpNxoEYRU/)
2. Planning and development is explained according to the [5Ss of UI/UX design](https://www.productleadership.com/resources/guides/navigating-the-5s-model-in-ux-ui-design/)

### Tasks

- [x] Strategy: target audience, Unique Selling Points
- [x] Scope: User Stories & prioritization
- [x] Structure
  - [x] Data models
  - [x] UI information design
  - [x] Account management
  - [x] CRUD functionalities

- [x] Skeleton: wireframes
- [x] Surface: 
  - [x] colors
  - [x] logo
  - [x] content
  - [x] title
