### ISSUE TITLE
USER STORY: README | Deployment

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#143]
As a **Developer**,

I want to **document the deployment process**,

so that **readers can replicate it**

### Acceptance Criteria

1. All steps in the deployment process are documented

### Tasks

- [x] Prerequisites
- [x] Cloning the repository
- [x] Forking the repository
- [x] Local deployment on GitPod
- [x] Deployment on Heroku
