### ISSUE TITLE
USER STORY: Navigate between different parts of the page

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#23]
As a **Visitor**,

I want to **navigate between different parts of the page**,

so that **I can always find the content I'm looking for**

### Acceptance Criteria

1. A Visitor to the site can easily view the parts of the page they chose]
2. A Visitor to the site cannot see content that is restricted to logged-in users only

### Tasks

- [x] add `base.html` to newly created `templates` directory
- [x] add [boilerplate code](https://github.com/Code-Institute-Solutions/blog/blob/main/08_templates/01_base_template/base.html) to file
- [x] customize nav bar
