### ISSUE TITLE
USER STORY: View About information

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#26]
As a **Visitor**,

I want to **read the About profile of the site owner**,

so that **can learn more about them**

### Acceptance Criteria

1. The site owner's About information is visible without having to log in.

### Tasks

- [ ] create a view in community/views.py
- [ ]  register URLs in in community/urls.py
- [ ]  register URLs in in spicy/urls.py (check if already done for #40 )
- [ ]  create a template: `community/templates/community/about.html
- [ ]  style template
- [ ]  make template responsive
