### ISSUE TITLE
USER STORY: Delete any user's Profile info

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#39]
As an **Admin**,

I want to **delete any user's Profile info**,

so that **obsolete information is removed**

### Acceptance Criteria

1. A logged-in Admin can delete any user's Profile info

### Tasks

- [x] log in as Admin to the site on Gitpod
- [x] delete a profile
- [x] check if change is visible on Heroku

#### Test on Prod

- [x] log in as Admin to the site on Heroku
- [x] delete a profile
- [x] check if change is visible on Gitpod
