### ISSUE TITLE
USER STORY: View a list of all profiles

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#40]
As a **Visitor**,

I want to **View a list of all profiles of community members**,

so that **I can learn about the content creators and visitors of the site**

### Acceptance Criteria

1. The list of all profiles is visible without having to log in

### Tasks

- [x] create a view in `community/views.py`
- [x] register URLs in  in `community/urls.py`
- [x] register URLs in  in `spicy/urls.py`
- [x] create  a template :`community/templates/community/profiles.html`
- [x] style template
- [x] make template responsive
