### ISSUE TITLE
USER STORY: View detailed profiles

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#43]
As a **Visitor**,

I want to **view user profiles**,

so that **I can learn about the community**

### Acceptance Criteria

1. A Visitor can view the profiles of users who chose to create one without logging in

### Tasks

- [x] create a view in community/views.py
- [x]  register URLs in in community/urls.py
- [x]  register URLs in in spicy/urls.py (check if already done for #40 )
- [x]  create a template :community/templates/community/profile_detail.html
- [x]  style template
- [x]  make template responsive
