### ISSUE TITLE
USER STORY: Reset own password

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#48]
As a **previously registered Visitor**,

I want to **reset my own password**,

so that **I can restore my access to my account in case I lose access to my password**

### Acceptance Criteria

1. A previously registered Visitor who has confirmed their account can submit their email address to receive a password reset link
2. A previously registered Visitor who has not confirmed their account receives a verification email instead
3. A Visitor who has not registered receives an email informing of the password reset attempt
4. The link to the password reset page is available from the login page
5. The link to the password reset page is available from the signup page.

### Tasks

- [x] look up URL in [Allauth documentation](https://docs.allauth.org/en/latest/account/views.html), under Password Reset
- [x] modify `templates/account/login.html` and `templates/account/signup.html` to include link to password reset page: `href="{% url 'account_reset_password' %}"`
- [x] update styling of password reset page `templates/account/password_reset.html`
- [x] test on Dev
- [x] deploy to Heroku
- [x] test on Prod:
  - [x] Registered & verified user
  - [x] Registered & unverified user
  - [x] Unregistered user

**Comment by blahosyl** [comment]
Blocked by #103
