### ISSUE TITLE
USER STORY: Edit own recipe

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#54]
As a **Collaborator**,

I want to **edit my own recipe**,

so that **I can correct the site content**

### Acceptance Criteria

1. Collaborators can edit their own recipe (draft)
2. Collaborators cannot edit recipe(draft)s for other users

### Tasks

- [x] complete setup in #121 
- [x] check if Recipe model is visible in the dev admin interface when logged in as a Staff user
- [x] `DEBUG= False`
- [x] deploy to Heroku
- [x] check if Recipe model is visible in the Heroku admin interface

#### Test on Dev
- [x] log in as Staff to the site on Gitpod
- [x] edit a recipe
- [x] check that you can only select the logged-in user as the author
- [x] check if change is visible on Heroku
- [x] check if change is visible on the site in Dev

#### Test on Prod
- [x] log in as Staff to the site on Heroku
- [x] edit a recipe
- [x] check that you can only select the logged-in user as the author
- [x] check if change is visible on Gitpod
- [x] check if change is visible on the site in Prod
