### ISSUE TITLE
USER STORY: Manual feature testing

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#67]
As a **Developer**,

I want to **manually test all features of the project**,

so that **I can make sure everything works as intended and uncover any bugs**

### Acceptance Criteria

1. All features of the project are manually tested
2. Any bugs are documented in an Issue

### Tasks

- [x] nav bar mobile
- [x] nav bar desktop
- [x] user bar
- [x] footer
- [x] home page
- [x] singin page
- [x] signup page
- [x] signout page
- [x] email sent page
- [x] password reset page
- [x] recipe detail page
  - [x] add comment
  - [x] edit comment
  - [x] delete comment
- [x] community page/profile list
- [x] profile detail page

**Comment by blahosyl** [comment]
All manual tests pass, test cases documented with videos and screenshots in TESTING.md.

See also #144
