### ISSUE TITLE
USER STORY: Connect external database

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#69]
As a **Deveoper**,

I want to **use an external database for my app**,

so that **I can make full use of its functionality**

### Acceptance Criteria

1. The external database created can be updated by the app.
2. I can log in with superuser credentials on the local environment
3. I can log in with superuser credentials on Heroku

### Tasks

- [x] create Neon database

#### Local config

- [x] store database URL in `env.py`
- [x] make sure `env.py` is in `.gitignore`
- [x] connect Neon database to app
- [x] create superuser
- [x] create local Secret Key
- [x] check you can log in to `<local app URL>/admin` with superuser credentials

#### Heroku config

- [x] set `DEBUG = False`
- [x] deploy to Heroku
- [x] add database URL to Heroku config vars
- [x] create Heroku Secret Key
- [x] check you can log in to `<Heroku app URL>/admin` with superuser credentials
