### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#7]
As a **Visitor with a user account**,

I want to **log in to my account**,

so that **I can comment on the recipes**

### Acceptance Criteria

1. A Visitor who has a user account can log in with their credentials (username and password)

### Tasks

- [x] prerequisite: setup described in #6 
- [x] in the newly copied `templates/account/login.html`, replace code with provided [boilerplate code]( https://github.com/Code-Institute-Solutions/blog/blob/main/11_authorisation/01_allauth/templates/account/login.html)
- [x] change text in boilerplate login code to match current project
- [x] run the server again: `python3 manage.py runserver` and check that the login and logout pages are styled according to the project's specification
- [x] in `base.html`, add message depending on whether a user is logged in or not
- [x] check that login works as intended

**Comment by blahosyl** [comment]
- [commit](https://github.com/blahosyl/spicy/commit/aa5bc716f090273523a1b8ac9ad62b51fca41097)
- [commit](https://github.com/blahosyl/spicy/commit/fe8ab4b361b68027f312ae3315b7138e1f8f89a3)
