### ISSUE TITLE
USER STORY: Create new ingredient (Collaborator)

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#71]
As a **Collaborator**,

I want to **create a new ingredient**,

so that **it can be used with recipes**

### Acceptance Criteria

1. A logged-in Collaborator can create a new ingredient
2. The new ingredient is available to all Collaborators and Admins

### Tasks

- [x] complete setup in #121 
- [x] check if Ingredient model is visible in the dev admin interface when logged in as a Staff user
- [x] `DEBUG= False`
- [x] deploy to Heroku
- [x] check if Ingredient model is visible in the Heroku admin interface

#### Test on Dev 

- [x] log in as Staff to the site on Gitpod
- [x] create a new ingredient
- [x] check if change is visible on Heroku
- [x] log in and log out as another user
- [x] check that the newly created ingredient is visible in the Admin panel  

#### Test on Prod

- [x] log in as Staff to the site on Heroku
- [x] create a new ingredient
- [x] check if change is visible on Gitpod
- [x] log in and log out as another user
- [x] check that the newly created ingredient is visible in the Admin panel
