### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#8]
As a **Logged-in User**,

I want to **log out of my account**,

so that **I can reduce the chance of my account being misused**

### Acceptance Criteria

1. A Logged-in User can log out of their account

### Tasks

- [x] prerequisite: setup described in #6 
- [x] in the newly copied `templates/account/logouttml`, replace code with provided [boilerplate code]( https://github.com/Code-Institute-Solutions/blog/blob/main/11_authorisation/01_allauth/templates/account/login.html)
- [x] change text in boilerplate login code to match current project
- [x] run the server again: `python3 manage.py runserver` and check that the login and logout pages are styled according to the project's specification
- [x] in `base.html`, add message depending on whether a user is logged in or not
- [x] check if logout works as intended

**Comment by blahosyl** [comment]
- [commit](https://github.com/blahosyl/spicy/commit/aa5bc716f090273523a1b8ac9ad62b51fca41097)
- [commit](https://github.com/blahosyl/spicy/commit/fe8ab4b361b68027f312ae3315b7138e1f8f89a3)
