### ISSUE TITLE
USER STORY: View ingredient quantities of own recipe

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#83]
As a **Collaborator**,

I want to **view the ingredient quantity item sfor their own recipe**,

so that **I can make sure it is accurate**

### Acceptance Criteria

1. A logged-in Collaborator can view the ingredient quantity items for their own recipe, even if it is not published.
2. A logged-in Collaborator cannot view the ingredient quantity items other users' own recipes on the admin interface.

### Acceptance Criteria

1. Collaborators can view ingredient quantities for their own recipes
2. Collaborators cannot view ingredient quantities for other users' recipes

### Tasks

- [x] complete setup in #121 
- [x] check if Ingredient quantity model is visible in the dev admin interface when logged in as a Staff user
- [x] `DEBUG= False`
- [x] deploy to Heroku
- [x] check if Ingredient quantity model is visible in the Heroku admin interface

#### Test on Dev
- [x] log in as Staff to the site on Gitpod
- [x] view ingredient quantities for your recipes
- [x] check that you can only view the logged-in user's ingredient quantities
- [x] check if change is visible on Heroku

#### Test on Prod
- [x] log in as Staff to the site on Heroku
- [x] view ingredient quantities for your recipes
- [x] check that you can only view the logged-in user's ingredient quantities
- [x] check if change is visible on Gitpod
