### ISSUE TITLE
USER STORY: Delete the ingredient quantities from own recipe

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#85]
As a **Collaborator**,

I want to **delete the ingredient quantity items from their own recipe**,

so that **the information is kept up to date**

### Acceptance Criteria

1. A logged-in Collaborator can delete the ingredient quantity items from their own recipe, even if it is not published.
2. A logged-in Collaborator cannot delete the ingredient quantity items other users' own recipes.

### Tasks

- [x] complete setup in #121 
- [x] check if Ingredient quantity model is visible in the dev admin interface when logged in as a Staff user
- [x] `DEBUG= False`
- [x] deploy to Heroku
- [x] check if Ingredient quantity model is visible in the Heroku admin interface

#### Test on Dev
- [x] log in as Staff to the site on Gitpod
- [x] delete ingredient quantities for your recipes
- [x] check that you can only delete the logged-in user's ingredient quantities
- [x] check if change is visible on Heroku
- [x] check if change is visible on the site in Dev

#### Test on Prod
- [x] log in as Staff to the site on Heroku
- [x] delete ingredient quantities for your recipes
- [x] check that you can only delete the logged-in user's ingredient quantities
- [x] check if change is visible on Gitpod
- [x] check if change is visible on the site in Prod
