### ISSUE TITLE
USER STORY: View list of ingredients (Collaborator)

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#89]
As a Collaborator,

I want to view the list of ingredients,

so that I know whether I need to add a new ingredient for my recipe or not

### Acceptance Criteria
1. A logged-in Collaborator can view the list of ingredients (added by any user)

### Tasks

- [x] complete setup in #121 
- [x] check if Ingredient model is visible in the dev admin interface when logged in as a Staff user
- [x] `DEBUG= False`
- [x] deploy to Heroku
- [x] check if Ingredient model is visible in the Heroku admin interface

#### Test on Dev 

- [x] log in as Staff to the site on Gitpod
- [x] check that you can see the list of ingredients

#### Test on Prod

- [x] log in as Staff to the site on Heroku
- [x] check that you can see the list of ingredients
