### ISSUE TITLE
USER STORY: Create file structure for CSS

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#93]
As a **Developer**,

I want to **have the  CSS styles available to all HTML files**,

so that **the app has a unified look**

### Acceptance Criteria

1. The styling defined in the project's CSS file applies to all HTML files

### Tasks

- [x] create `style.css` in the directory `static/css`
- [x] add [boilerplate code](https://github.com/Code-Institute-Solutions/blog/blob/main/08_templates/01_base_template/style.css)
- [x] build a path for the `static` directory in `settings.py`: `STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]`
- [x] `load static ` in `base.html`
- [x] add link to CSS file in `base.html`: `<link rel="stylesheet" href="{% static 'css/style.css' %}">`
