### ISSUE TITLE
USER STORY: Customize styling of individual recipe pages

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#95]
As a **Site Owner**,

I want to **display individual recipes with distinctive, customized and responsive styling**,

so that **I facilitate a positive user experience**

### Acceptance Criteria

1. The visual styling of individual recipe pages is distinctive
2. The styling is consistent with the rest of the site
3. The styling is responsive on all devices with a minimum viewport width of 320 px
### Tasks

- [x] check color contrasts with accessibility checker, adjust palette
- [x] use color variables in CSS
- [x] unify color palette
- [x] adjust spacing & alignment
- [x] add picture to XS & S viewports

**Comment by blahosyl** [comment]
Blocked by #99

**Comment by blahosyl** [comment]
Adjust styling once content is finalized, especially if implementing #101
