### ISSUE TITLE
USER STORY: Choose color themes

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/spicy#98]
As a **Visitor**,

I want to **choose between different color themes**,

so that **I can tailor the visual input to my needs**

### Acceptance Criteria

1. A visitor can select between different color schemes for the app

### Tasks

- [x] create color drop-down in `base.html`
- [x] write JS code that changes CSS variables based on the option selected in the drop-down ([resource](https://www.toptal.com/front-end/dynamic-css-with-custom-properties))
- [x] make color theme selection persistent across pages 
- [x] define and implement at least 2 different color themes

**Comment by blahosyl** [comment]
My mentor suggested using [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) in JS for making the color theme selection consistent. 

Tried to implement in based on the [extended documentation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API), does not work so far.
